# Generated by Django 4.2.4 on 2023-09-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='club_members',
            field=models.CharField(max_length=100),
        ),
    ]
