# Generated by Django 4.2.4 on 2023-09-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_csvfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='group',
            field=models.CharField(max_length=100),
        ),
    ]
